### ISSUE TITLE
How to set the window size...I'm a novice

### ISSUE THREAD

**Issue by Botreechan** [mherrmann/selenium-python-helium#18]

**Comment by mherrmann** [comment]
Please Google "Selenium set window size". This will tell you how to do this for a "web driver". To get Helium's web driver, you can use `get_driver()`. If you want to set the window size when starting the browser (instead of when it already runs), you may find [this](https://github.com/mherrmann/selenium-python-helium/releases/tag/v3.0.2) interesting.

For further questions, please ask on StackOverflow.

**Comment by Botreechan** [comment]
Thank you for your reply, I have got it.
